# Generated by Django 4.2.20 on 2025-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
