# Generated by Django 4.2.20 on 2025-04-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='imgae',
            new_name='image',
        ),
    ]
